### ISSUE TITLE
Allow to squash pr then rebase before merge.

### ISSUE THREAD

**Issue by AraHaan** [waldobronchart/git-pr-linear-merge#1]
I would love to have a version of this that can squash the commits that the pr adds (only the commits that is not in the target branch) BEFORE rebasing and then merging. Also I would like it where we can turn off the merge commits when merging if we do not want it but instead a single commit per pr no matter what size the pr actually is.

See also: https://github.com/isaacs/github/issues/1968

**Comment by waldobronchart** [comment]
I've implemented this now 👍 

https://github.com/waldobronchart/git-pr-linear-merge#squash-command
